sonar.projectKey=Nachobt98_sportProject
sonar.organization=nachobt98

sonar.sources=src,backend/src
sonar.tests=src,backend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx
sonar.exclusions=**/node_modules/**,build/**,dist/**,coverage/**,public/**,**/*.config.js,**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx,src/img/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.ico,**/*.svg
sonar.coverage.exclusions=backend/server.js,backend/src/server.js,backend/src/app.js,backend/src/config/**,backend/src/routes/**,backend/src/models/**,src/index.jsx,src/reportWebVitals.js,src/setupTests.js,src/__mocks__/**,**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
